In [1]:
import numpy as np

In [2]:
### MNIST data downlaoding ####

In [3]:
import keras as ks

2024-06-02 10:58:33.426862: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
from keras.datasets import mnist

In [5]:
(train_images,train_labels),(test_images,test_labels)=mnist.load_data()

In [6]:
train_images.ndim

3

In [7]:
train_images.shape

(60000, 28, 28)

In [8]:
np.shape(train_images)

(60000, 28, 28)

In [9]:
train_images.dtype

dtype('uint8')

In [10]:
###3 normalizing the data ####
train_images = train_images.reshape((60000,28*28))
train_images = train_images.astype('float32')/255

In [11]:
train_images.shape

(60000, 784)

In [12]:
train_images.ndim

2

In [13]:
train_labels.shape

(60000,)

In [14]:
test_images = test_images.reshape((10000,28*28))
test_images = test_images.astype('float32')/255

In [15]:
test_images.shape

(10000, 784)

In [16]:
test_images.ndim

2

In [17]:
#### constructing the DL model #####

In [18]:
from keras import models
from keras import layers

In [19]:
network = models.Sequential()

In [20]:
network.add(layers.Dense(512 ,activation='relu', input_shape =(28*28,)))

In [21]:
network.add(layers.Dense(10 , activation='softmax'))

In [22]:
network.compile(optimizer='rmsprop',loss = 'categorical_crossentropy',metrics=['accuracy'])

In [23]:
from keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [24]:
network.fit(train_images,train_labels,epochs=10,batch_size=128)

2024-06-02 10:58:45.055749: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 188160000 exceeds 10% of free system memory.


Epoch 1/10
469/469 [==============================] - 7s 12ms/step - loss: 0.2630 - accuracy: 0.9250
Epoch 2/10
469/469 [==============================] - 5s 11ms/step - loss: 0.1066 - accuracy: 0.9688
Epoch 3/10
469/469 [==============================] - 6s 13ms/step - loss: 0.0706 - accuracy: 0.9785
Epoch 4/10
469/469 [==============================] - 5s 11ms/step - loss: 0.0515 - accuracy: 0.9846
Epoch 5/10
469/469 [==============================] - 6s 12ms/step - loss: 0.0389 - accuracy: 0.9883
Epoch 6/10
469/469 [==============================] - 6s 12ms/step - loss: 0.0293 - accuracy: 0.9913
Epoch 7/10
469/469 [==============================] - 5s 12ms/step - loss: 0.0230 - accuracy: 0.9933
Epoch 8/10
469/469 [==============================] - 7s 14ms/step - loss: 0.0175 - accuracy: 0.9951
Epoch 9/10
469/469 [==============================] - 6s 13ms/step - loss: 0.0127 - accuracy: 0.9967
Epoch 10/10
469/469 [==============================] - 6s 13ms/step - loss: 0.0097 - accura

In [26]:
network.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 512)               401920    
                                                                 
 dense_1 (Dense)             (None, 10)                5130      
                                                                 
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


In [28]:
network.get_weights()

[array([[ 0.05898678, -0.0022513 , -0.05029362, ..., -0.05933507,
         -0.02335175,  0.03995271],
        [-0.03014474,  0.0502866 ,  0.03269792, ...,  0.02524122,
         -0.02114493,  0.05788235],
        [ 0.01297068, -0.04765457,  0.06433137, ..., -0.05784724,
         -0.02625886,  0.06168494],
        ...,
        [-0.05090324,  0.03684305,  0.06754871, ..., -0.00499255,
         -0.01710176,  0.05256833],
        [ 0.05846299,  0.00438971, -0.05805089, ...,  0.03185724,
          0.05026471, -0.03231405],
        [ 0.04602848, -0.05581539,  0.00346062, ...,  0.04714073,
         -0.02464256,  0.06192523]], dtype=float32),
 array([ 1.79527961e-02,  1.88225973e-02,  5.66280074e-02, -5.91251254e-02,
         3.92073840e-02,  6.72287345e-02, -3.47252339e-02, -3.63907311e-03,
        -9.49300639e-03, -2.62498129e-02,  4.93171178e-02,  5.21302335e-02,
         2.05105711e-02, -2.75645722e-02,  5.46612702e-02,  4.31011803e-02,
         1.32186711e-02,  2.17498634e-02, -1.13356048e

In [35]:
network.get_weights()[0]

array([[ 0.05898678, -0.0022513 , -0.05029362, ..., -0.05933507,
        -0.02335175,  0.03995271],
       [-0.03014474,  0.0502866 ,  0.03269792, ...,  0.02524122,
        -0.02114493,  0.05788235],
       [ 0.01297068, -0.04765457,  0.06433137, ..., -0.05784724,
        -0.02625886,  0.06168494],
       ...,
       [-0.05090324,  0.03684305,  0.06754871, ..., -0.00499255,
        -0.01710176,  0.05256833],
       [ 0.05846299,  0.00438971, -0.05805089, ...,  0.03185724,
         0.05026471, -0.03231405],
       [ 0.04602848, -0.05581539,  0.00346062, ...,  0.04714073,
        -0.02464256,  0.06192523]], dtype=float32)

In [36]:
network.get_weights()[1]

array([ 1.79527961e-02,  1.88225973e-02,  5.66280074e-02, -5.91251254e-02,
        3.92073840e-02,  6.72287345e-02, -3.47252339e-02, -3.63907311e-03,
       -9.49300639e-03, -2.62498129e-02,  4.93171178e-02,  5.21302335e-02,
        2.05105711e-02, -2.75645722e-02,  5.46612702e-02,  4.31011803e-02,
        1.32186711e-02,  2.17498634e-02, -1.13356048e-02, -3.80815864e-02,
        4.07467186e-02,  2.63680723e-02, -6.18645251e-02,  3.95239629e-02,
       -1.81790907e-02,  2.71896794e-02,  1.87091380e-02, -1.25858365e-02,
        1.91000309e-02, -2.20717695e-02, -7.62999244e-03,  5.57919126e-03,
        9.45289340e-03, -1.40751945e-02, -5.22040436e-03,  7.75641575e-02,
        5.30655533e-02,  1.90499853e-02, -2.22613662e-02,  4.31512669e-02,
        1.33305239e-02, -2.78675258e-02, -4.07557748e-02,  7.71572590e-02,
        3.23809460e-02,  2.58999914e-02, -5.76795563e-02,  8.66596550e-02,
        7.22571984e-02, -1.83381289e-02,  3.17648649e-02, -1.36606619e-02,
       -3.18389237e-02,  

In [37]:
network.get_weights()[2]

array([[-0.34660944, -0.201116  , -0.43846768, ..., -0.12933227,
         0.11636526, -0.15114544],
       [-0.4780082 ,  0.09048913,  0.01473406, ...,  0.10228621,
         0.0712513 ,  0.05281112],
       [-0.37862548,  0.02189267, -0.5836966 , ..., -0.08499828,
         0.04852448,  0.04176099],
       ...,
       [ 0.11604872, -0.36780336, -0.25826958, ..., -0.07390154,
        -0.06910569, -0.02715042],
       [ 0.04413434, -0.05265639, -0.01386897, ..., -0.04014273,
        -0.07957106,  0.05919425],
       [ 0.24387263, -0.2891022 , -0.59555197, ...,  0.1174598 ,
        -0.13890892, -0.1836654 ]], dtype=float32)

In [38]:
network.get_weights()[3]

array([-0.09208178, -0.05620029, -0.03782693,  0.00339389,  0.00229185,
        0.01373721, -0.03932734, -0.06512167,  0.08877447,  0.02953787],
      dtype=float32)

In [39]:
### digits visulaization ###
import matplotlib.pyplot as plt